substitutions:
  _TEST_IMAGE_TAG: 'gcri.io/hosting-38998/wallme/pytest'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file'
      - 'Dockerfile.pytest'
      - '--tag'
      - '${_TEST_IMAGE_TAG}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_TEST_IMAGE_TAG}'
  - name: '${_TEST_IMAGE_TAG}'
    args: [ ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'functions'
      - 'deploy'
      - 'wallme'
      - '--trigger-topic'
      - 'gmail-alerts'
      - '--runtime'
      - 'python37'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '128MB'
      - '--source'
      - '.'

