
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'functions'
      - 'deploy'
      - 'wallme'
      - '--runtime'
      - 'python37'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '128MB'
      - '--source'
      - '.'

