
substitutions:
  _TAG: gcr.io/hosting-38998/wallme

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "build", "--tag", "${_TAG}", "." ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "push", "${_TAG}" ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'wallme'
      - '--image'
      - '${_TAG}'
      - '--region'
      - '${us-central1}'
      - '--platform'
      - 'managed'

